# Generated by Django 5.2.8 on 2025-11-05 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4')], unique=True)),
            ],
            options={
                'verbose_name_plural': 'Academic Years',
                'ordering': ['year_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MST1', 'Mid Semester Test 1'), ('MST2', 'Mid Semester Test 2'), ('EST', 'End Semester Test')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.academicyear')),
            ],
            options={
                'ordering': ['year__year_number', 'semester_number'],
                'unique_together': {('year', 'semester_number')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('book_recommendation', models.CharField(blank=True, help_text="e.g., 'Computer Organization by Hamacher'", max_length=200)),
                ('book_pages', models.CharField(blank=True, help_text="e.g., 'pp. 45–67'", max_length=100)),
                ('video_url', models.URLField(blank=True, help_text='YouTube embed link (e.g., https://www.youtube.com/embed/abc123)')),
                ('practice_sheet', models.FileField(blank=True, null=True, upload_to='practice_sheets/')),
                ('pyq_pdf', models.FileField(blank=True, null=True, upload_to='pyqs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_premium', models.BooleanField(default=True, help_text='Only premium users can access this')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.examtype')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.semester')),
            ],
            options={
                'ordering': ['semester__year__year_number', 'semester__semester_number', 'exam_type'],
            },
        ),
    ]
