# Generated by Django 5.2.7 on 2025-11-07 19:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_resource_practice_sheet_alter_resource_pyq_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='practice_sheet',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pyq_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
