# Generated by Django 5.2.7 on 2025-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_resource_practice_sheet_alter_resource_pyq_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='practice_sheet',
            field=models.FileField(blank=True, null=True, upload_to='practice_sheets/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='pyq_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pyqs/'),
        ),
    ]
